avatar: "" # 头像已隐藏
background: # 既是博客的背景，又是文章默认头图
    path: https://glitchedreme.github.io/SlayTheSpire2ModdingTutorials/images/qq20260307.png
    width: 1600
    height: 900
favicon:
    href: /SlayTheSpire2ModdingTutorials/icon.ico # 网站图标
    type: image/x-icon # 图标类型，可能的值有(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

# 附加图标库 使用说明：https://kira.host/hexo/config/icon.html
# iconlib: //at.alicdn.com/t/font_3299330_el19bsi97h8.css

cdn: # 这里可以修改站点使用的库的CDN
    gitalk:
        css: https://unpkg.com/gitalk@latest/dist/gitalk.css
        js: https://unpkg.com/gitalk@latest/dist/gitalk.min.js
    giscus:
        js: https://giscus.app/client.js

menu:
    教程目录:
        - /
        - icon-book
    GitHub:
        - https://github.com/GlitchedReme/SlayTheSpire2ModdingTutorials
        - icon-github

docsTree:
    [
        { title: 首页, path: /, icon: icon-home },
        {
            title: 基础,
            open: true,
            children:
                [
                    { title: 01 环境配置, path: /docs/01-env-setup/ },
                    {
                        title: 02 常见问题,
                        path: /docs/02-install-view-source-and-patch/,
                    },
                    {
                        title: 03 选择基础库,
                        path: /docs/03-choose-base-library/,
                    },
                    {
                        title: 04 变量与描述,
                        path: /docs/05-variable-and-description/,
                    },
                    { title: 05 先古对话, path: /docs/08-ancient-dialogue/ },
                    {
                        title: 06 快速调试&热重载,
                        path: /docs/07-quick-debug-and-hot-reload/,
                    },
                    { title: 07 启动项参数, path: /docs/08-launch-arguments/ },
                    { title: 08 控制台指令, path: /docs/09-console-commands/ },
                    { title: 09 Patch, path: /docs/10-patch/ },
                ],
        },
        {
            title: RitsuLib,
            open: true,
            children:
                [
                    { title: 00 总览, path: /docs/04-ritsulib/ },
                    {
                        title: 01 添加基础内容,
                        open: true,
                        children:
                            [
                                { title: 01 添加卡牌, path: /docs/04-ritsulib/04-01-add-card/ },
                                { title: 02 自定义配置, path: /docs/04-ritsulib/04-02-custom-config/ },
                                { title: 03 添加新遗物, path: /docs/04-ritsulib/04-03-add-relic/ },
                                { title: 04 添加卡牌属性, path: /docs/04-ritsulib/04-04-card-properties/ },
                                { title: 05 添加新能力, path: /docs/04-ritsulib/04-05-add-power/ },
                                { title: 06 添加新药水, path: /docs/04-ritsulib/04-06-add-potion/ },
                                { title: 07 添加先古之民, path: /docs/04-ritsulib/04-07-add-ancient/ },
                                { title: 08 添加充能球, path: /docs/04-ritsulib/04-08-add-orb/ },
                                { title: 09 添加时间线, path: /docs/04-ritsulib/04-09-add-timeline/ },
                                { title: 10 添加音频, path: /docs/04-ritsulib/04-10-add-audio/ },
                                { title: 11 添加新怪物, path: /docs/04-ritsulib/04-11-add-monster/ },
                                { title: 12 添加新事件, path: /docs/04-ritsulib/04-12-add-event/ },
                                { title: 13 添加新附魔, path: /docs/04-ritsulib/04-13-add-enchantment/ },
                                { title: 14 添加新人物, path: /docs/04-ritsulib/04-14-add-new-character/ },
                                { title: 15 添加单例, path: /docs/04-ritsulib/04-15-add-singleton/ },
                            ],
                    },
                    {
                        title: 02 玩法基底,
                        open: false,
                        children:
                            [
                                { title: 01 血条覆盖, path: /docs/04-ritsulib/04-16-health-bar-overlay/ },
                                { title: 02 手牌上限, path: /docs/04-ritsulib/04-18-max-hand-size/ },
                                { title: 03 手牌泛光, path: /docs/04-ritsulib/04-19-hand-outline/ },
                                { title: 04 自定义卡牌堆, path: /docs/04-ritsulib/04-20-custom-card-pile/ },
                                { title: 05 顶栏按钮, path: /docs/04-ritsulib/04-21-top-bar-button/ },
                                { title: 06 通知提示, path: /docs/04-ritsulib/04-22-notification/ },
                            ],
                    },
                    {
                        title: 03 模组工具,
                        open: false,
                        children:
                            [
                                { title: 01 数据保存, path: /docs/04-ritsulib/04-17-data-save/ },
                                { title: 02 生命周期事件, path: /docs/04-ritsulib/04-23-lifecycle-events/ },
                                { title: 03 补丁系统, path: /docs/04-ritsulib/04-24-patch-system/ },
                                { title: 04 数据持久化, path: /docs/04-ritsulib/04-25-data-persistence/ },
                                { title: 05 运行时热键, path: /docs/04-ritsulib/04-26-runtime-hotkey/ },
                            ],
                    },
                ],
        },
        {
            title: BaseLib,
            open: false,
            children:
                [
                    { title: 00 总览, path: /docs/03-baselib/ },
                    { title: 01 添加卡牌, path: /docs/03-baselib/03-01-add-card/ },
                    { title: 02 自定义模组配置, path: /docs/03-baselib/03-02-mod-config/ },
                    { title: 03 添加新遗物, path: /docs/03-baselib/03-03-add-relic/ },
                    { title: 04 添加卡牌属性, path: /docs/03-baselib/03-04-card-properties/ },
                    { title: 05 添加新能力, path: /docs/03-baselib/03-05-add-power/ },
                    { title: 06 添加新药水, path: /docs/03-baselib/03-06-add-potion/ },
                    { title: 07 添加先古之民, path: /docs/03-baselib/03-07-add-ancient/ },
                    { title: 08 添加充能球, path: /docs/03-baselib/03-08-add-orb/ },
                    { title: 09 局内保存, path: /docs/03-baselib/03-09-run-save/ },
                    { title: 10 mod联动, path: /docs/03-baselib/03-10-mod-integration/ },
                    { title: 11 添加新怪物, path: /docs/03-baselib/03-11-add-monster/ },
                    { title: 12 添加新事件, path: /docs/03-baselib/03-12-add-event/ },
                    { title: 13 添加新附魔, path: /docs/03-baselib/03-13-add-enchantment/ },
                    { title: 14 添加新人物, path: /docs/04-add-new-character/ },
                    { title: 15 添加单例, path: /docs/03-baselib/03-15-add-singleton/ },
                    { title: 16 手牌上限, path: /docs/03-baselib/03-16-max-hand-size/ },
                ],
        },
        {
            title: 迁移,
            open: true,
            children:
                [
                    { title: 01 测试版 至 正式版, path: /docs/07-migration-99-100/ },
                    {
                        title: 02 BaseLib 至 RitsuLib,
                        path: /docs/08-migration-baselib-to-ritsulib/,
                    },
                ],
        },
        {
            title: 视觉,
            open: false,
            children:
                [
                    {
                        title: 01 卡图&Spine,
                        path: /docs/05-card-art-and-skin-replacement/,
                    },
                    {
                        title: 02 风格原画绘制,
                        path: /docs/06-style-art-drawing/,
                    },
                ],
        },
    ]

widgets: []

maxTagcloud: 0 # 标签云组件显示的标签数量，0 表示不限制

social:
    GitHub:
        - https://github.com/GlitchedReme/SlayTheSpire2ModdingTutorials
        - icon-github
        - "#ffffff"
        - "#24292e"
    QQ群:
        - "#qq-group"
        - icon-comment
        - "#ffffff"
        - "#12b7f5"

color: # 配色方案，从first到seventh为优先级为1-7的颜色，默认为彩虹配色
    first: # 同时作为主题色
        r: 187
        g: 101
        b: 22
    second:
        r: 64
        g: 82
        b: 108
    third:
        r: 217
        g: 117
        b: 25
    fourth:
        r: 98
        g: 118
        b: 146
    fifth:
        r: 55
        g: 44
        b: 72
    sixth:
        r: 179
        g: 104
        b: 70
    seventh:
        r: 44
        g: 164
        b: 191

# 评论区
gitalk:
    active: false # 是否启用 gitalk
    admin: -your github username- # 拥有对该repo进行操作的 GitHub username
    owner: -your github username- # 持有该 repo 的 GitHub username
    repo: -issue repo name- # 存放评论的 issue 所在的 repo
    clientID: -id- # GitHub Client ID
    clientSecret: -key- # GitHub Client Secret
    title: "" # Gitalk Issue Title
giscus:
    active: true # 是否启用 giscus
    repo: GlitchedReme/SlayTheSpire2ModdingTutorials # 存放评论的 discus 所在的 repo
    repoID: R_kgDORf0PEA # GitHub repo ID
    category: Announcements # 选择新 discussions 所在的分类
    categoryID: DIC_kwDORf0PEM4C3zDO # 分类 ID
    mapping: pathname # pathname, url, title, og:title, specific, number
    # term: # abc 123 # specific | number
    strict: false
    reactions: true
    metadata: false
    theme: dark_dimmed
    lang: zh-CN

copyright: '<strong>版权声明：</strong>本文采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-hans" target="_blank">CC BY-NC-SA 4.0 CN</a> 协议进行许可'
copyTip: "著作权归作者所有。\n商业转载请联系作者获得授权，非商业转载请注明出处。\n来源：%url" # 自定义复制版权文案,使用 %url 代替当前页面URL, 修改为false禁用

# 自定义侧边栏尾部内容
sidebar: ""

busuanzi:
    active: true
    title: 访客统计

# 自定义样式
customStyles:
    - docs-nav

customScripts:
    - docs-anchors
    - docs-panels

# 友链配置
friends:
    # - avatar: <友链缩略图>
    #   link: <跳转连接>
    #   name: <名称>

# 可复制的代码块
copyableCodeblock: true
